### ISSUE TITLE
Résultats - Test (pour pierre)

### ISSUE THREAD

**Issue by moussaei** [moussaei/perscido#13]
- [x] scientific field: other: space causes error. no add button and feedback. sometimes also w/o space ! (ali jabbari)
- [x] related publications edit > does not point to right edit page (ali jabbari, saeed varasteh, Vera Shalaeva)
- [x] illustrated logo: thumbnail (ali jabbari)
- [x] when we wanted to upload a file for second time we have error. (saeed varasteh, ali jabber)
- [x] for “Illustrative logo”, “Readme file for your dataset” and “Data storage mode” what is the format acceptance ( .zip, .txt, .doc, ....). (saeed varasteh, ali jabbari, Vera Shalaeva)

**Comment by perscidoPHebert** [comment]
Illustrative logo”, Tous format image il n'y a pas lieu de le préciser
“Readme file for your dataset” Fichier text uniquement peut être faut il le préciser
  “Data storage mode” Fichier Ziup uniquement, peut être faut il le préciser
